export const SET_DEFINITIONS = "SET_DEFINITIONS";
export const READ_DEFINITIONS = "READ_DEFINITIONS";

export const SET_FLASHCONTENT = "SET_FLASHCONTENT";
export const READ_FLASHCONTENT = "READ_FLASHCONTENT";

export const SET_ACTIVE_WORD = "SET_ACTIVE_WORD";
